import * as React from "react";
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { render } from "@react-email/render";
import type { EmailTemplateName } from "@authhero/adapter-interfaces";
import { ResetEmail } from "../src/emails/defaults/ResetEmail";
import { ResetEmailByCode } from "../src/emails/defaults/ResetEmailByCode";
import { VerifyEmail } from "../src/emails/defaults/VerifyEmail";
import { VerifyEmailByCode } from "../src/emails/defaults/VerifyEmailByCode";
import { WelcomeEmail } from "../src/emails/defaults/WelcomeEmail";
import { UserInvitation } from "../src/emails/defaults/UserInvitation";
import { BlockedAccount } from "../src/emails/defaults/BlockedAccount";
import { StolenCredentials } from "../src/emails/defaults/StolenCredentials";
import { EnrollmentEmail } from "../src/emails/defaults/EnrollmentEmail";
import { MfaOobCode } from "../src/emails/defaults/MfaOobCode";
import { ChangePassword } from "../src/emails/defaults/ChangePassword";
import { PasswordReset } from "../src/emails/defaults/PasswordReset";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, "..", "src", "emails", "defaults", "compiled.ts");

const templates: Array<[EmailTemplateName, () => JSX.Element]> = [
  ["reset_email", ResetEmail],
  ["reset_email_by_code", ResetEmailByCode],
  ["verify_email", VerifyEmail],
  ["verify_email_by_code", VerifyEmailByCode],
  ["welcome_email", WelcomeEmail],
  ["user_invitation", UserInvitation],
  ["blocked_account", BlockedAccount],
  ["stolen_credentials", StolenCredentials],
  ["enrollment_email", EnrollmentEmail],
  ["mfa_oob_code", MfaOobCode],
  ["change_password", ChangePassword],
  ["password_reset", PasswordReset],
];

async function main() {
  const compiled: Record<string, string> = {};
  for (const [name, Component] of templates) {
    compiled[name] = await render(<Component />, { pretty: true });
  }

  const out = `// AUTO-GENERATED by scripts/build-emails.tsx. Do not edit by hand.
// Run \`pnpm build:emails\` to regenerate from src/emails/defaults/*.tsx.
import type { EmailTemplateName } from "@authhero/adapter-interfaces";

export const defaultBodies: Partial<Record<EmailTemplateName, string>> = ${JSON.stringify(
    compiled,
    null,
    2,
  )};
`;

  writeFileSync(outPath, out, "utf8");
  console.log(`Compiled ${templates.length} email templates → ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
