import { CacheAdapter } from "./Cache";
import { ClientsAdapter } from "./Clients";
import { ClientGrantsAdapter } from "./ClientGrants";
import { CodesAdapter } from "./Codes";
import { PasswordsAdapter } from "./Passwords";
import { SessionsAdapter } from "./Sessions";
import { TenantsDataAdapter } from "./Tenants";
import { UserDataAdapter } from "./Users";
import { LogsDataAdapter } from "./Logs";
import { ConnectionsAdapter } from "./Connections";
import { CustomDomainsAdapter } from "./CustomDomains";
import { KeysAdapter } from "./Keys";
import { BrandingAdapter } from "./Branding";
import { HooksAdapter } from "./Hooks";
import { LegacyClientsAdapter } from "./LegacyClients";
import { ThemesAdapter } from "./Themes";
import { LoginSessionsAdapter } from "./LoginSessions";
import { PromptSettingsAdapter } from "./PromptSettings";
import { EmailProvidersAdapter } from "./EmailProviders";
import { RefreshTokensAdapter } from "./RefreshTokens";
import { FormsAdapter } from "./Forms";
import { ResourceServersAdapter } from "./ResourceServers";
import { RolePermissionsAdapter } from "./RolePermissions";
import { UserPermissionsAdapter } from "./UserPermissions";
import { RolesAdapter } from "./Roles";
import { UserRolesAdapter } from "./UserRoles";
import { OrganizationsAdapter } from "./Organizations";
import { UserOrganizationsAdapter } from "./UserOrganizations";
import { TenantSettingsAdapter } from "./TenantSettings";

export interface DataAdapters {
  branding: BrandingAdapter;
  cache?: CacheAdapter;
  clients: ClientsAdapter;
  clientGrants: ClientGrantsAdapter;
  legacyClients: LegacyClientsAdapter;
  codes: CodesAdapter;
  connections: ConnectionsAdapter;
  customDomains: CustomDomainsAdapter;
  emailProviders: EmailProvidersAdapter;
  forms: FormsAdapter;
  hooks: HooksAdapter;
  keys: KeysAdapter;
  loginSessions: LoginSessionsAdapter;
  logs: LogsDataAdapter;
  passwords: PasswordsAdapter;
  promptSettings: PromptSettingsAdapter;
  refreshTokens: RefreshTokensAdapter;
  resourceServers: ResourceServersAdapter;
  rolePermissions: RolePermissionsAdapter;
  userPermissions: UserPermissionsAdapter;
  roles: RolesAdapter;
  sessions: SessionsAdapter;
  tenants: TenantsDataAdapter;
  tenantSettings: TenantSettingsAdapter;
  themes: ThemesAdapter;
  users: UserDataAdapter;
  userRoles: UserRolesAdapter;
  organizations: OrganizationsAdapter;
  userOrganizations: UserOrganizationsAdapter;
}

export * from "./Cache";
export * from "./Clients";
export * from "./ClientGrants";
export * from "./Keys";
export * from "./RolePermissions";
export * from "./UserPermissions";
export * from "./UserRoles";
export * from "./Organizations";
export * from "./UserOrganizations";
export * from "./TenantSettings";
