#!/usr/bin/env node
// Inline the admin UI (@authhero/admin dist) and the login widget
// (@authhero/widget dist) into the worker bundle — a dispatch vertical has no
// ASSETS binding, so the UI rides along as worker modules (the same pattern as
// substrat/console). Source maps are excluded: they are ~80% of admin's dist
// and serve no one in a worker bundle.
import { readdirSync, readFileSync, statSync, writeFileSync, existsSync, realpathSync } from "node:fs";
import { join, relative, extname, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const outFile = join(root, "src", "assets.generated.ts");

const adminDist = realpathSync(join(root, "..", "..", "apps", "admin")) + "/dist";
const widgetDist =
  realpathSync(join(root, "..", "..", "packages", "ui-widget")) + "/dist/authhero-widget";

const TEXT_TYPES = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".svg": "image/svg+xml",
  ".json": "application/json; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
  ".webmanifest": "application/manifest+json",
};
const BINARY_TYPES = {
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
};

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

function collect(dist) {
  const entries = [];
  let bytes = 0;
  if (!existsSync(dist)) return { entries, bytes, missing: true };
  for (const file of walk(dist)) {
    const ext = extname(file).toLowerCase();
    if (ext === ".map") continue; // never ship source maps in the bundle
    const urlPath = "/" + relative(dist, file).split("\\").join("/");
    if (TEXT_TYPES[ext]) {
      const body = readFileSync(file, "utf8");
      bytes += body.length;
      entries.push(`  ${JSON.stringify(urlPath)}: { body: ${JSON.stringify(body)}, encoding: 'utf8', type: ${JSON.stringify(TEXT_TYPES[ext])} },`);
    } else {
      const body = readFileSync(file).toString("base64");
      bytes += body.length;
      const type = BINARY_TYPES[ext] ?? "application/octet-stream";
      entries.push(`  ${JSON.stringify(urlPath)}: { body: ${JSON.stringify(body)}, encoding: 'base64', type: ${JSON.stringify(type)} },`);
    }
  }
  return { entries, bytes, missing: false };
}

const admin = collect(adminDist);
const widget = collect(widgetDist);
if (admin.missing) console.warn(`gen-assets: ${adminDist} missing — build apps/admin first (admin UI will 404)`);
if (widget.missing) console.warn(`gen-assets: ${widgetDist} missing — build @authhero/widget first (login widget will 404)`);

const next = `// GENERATED by scripts/gen-assets.mjs — DO NOT EDIT, do not commit.
export interface BundledAsset { body: string; encoding: 'utf8' | 'base64'; type: string; }
export const ADMIN_ASSETS: Record<string, BundledAsset> = {
${admin.entries.join("\n")}
};
export const WIDGET_ASSETS: Record<string, BundledAsset> = {
${widget.entries.join("\n")}
};
`;

const prev = existsSync(outFile) ? readFileSync(outFile, "utf8") : null;
if (prev === next) {
  console.log("gen-assets: unchanged");
} else {
  writeFileSync(outFile, next);
  console.log(
    `gen-assets: admin ${admin.entries.length} file(s) (${(admin.bytes / 1048576).toFixed(1)}MB raw), ` +
      `widget ${widget.entries.length} file(s) (${(widget.bytes / 1048576).toFixed(1)}MB raw)`,
  );
}
