#!/usr/bin/env node
// Generate src/assets.generated.ts from the built SPA (app/dist).
//
// A sandbox-clean vertical is pushed into the WFP dispatch namespace as a worker
// bundle; static assets are NOT an admissible binding there, so the SPA rides
// along as ordinary worker modules: every file under app/dist is inlined into one
// generated module the worker serves from (src/assets.ts). Pattern lifted from
// the CRM/meridian verticals.
//
// Runs before typecheck (empty map if app/dist is absent — keeps CI green) and
// after the app build in the wrangler build command (real content for the push).
import { readdirSync, readFileSync, statSync, writeFileSync, existsSync } from "node:fs";
import { join, relative, extname, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const distDir = join(here, "..", "app", "dist");
const outFile = join(here, "..", "src", "assets.generated.ts");

// Text types inline as UTF-8 literals; everything else as base64.
const TEXT_TYPES = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".svg": "image/svg+xml",
  ".json": "application/json; charset=utf-8",
  ".map": "application/json; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
  ".webmanifest": "application/manifest+json",
};
const BINARY_TYPES = {
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
};

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

const entries = [];
if (existsSync(distDir)) {
  for (const file of walk(distDir)) {
    const ext = extname(file).toLowerCase();
    const urlPath = "/" + relative(distDir, file).split("\\").join("/");
    if (TEXT_TYPES[ext]) {
      const body = readFileSync(file, "utf8");
      entries.push(`  ${JSON.stringify(urlPath)}: { body: ${JSON.stringify(body)}, encoding: 'utf8', type: ${JSON.stringify(TEXT_TYPES[ext])} },`);
    } else {
      const body = readFileSync(file).toString("base64");
      const type = BINARY_TYPES[ext] ?? "application/octet-stream";
      entries.push(`  ${JSON.stringify(urlPath)}: { body: ${JSON.stringify(body)}, encoding: 'base64', type: ${JSON.stringify(type)} },`);
    }
  }
}

const header = `// GENERATED by scripts/gen-assets.mjs from app/dist — DO NOT EDIT, do not commit.
export interface BundledAsset { body: string; encoding: 'utf8' | 'base64'; type: string; }
export const ASSETS: Record<string, BundledAsset> = {
`;

const next = header + entries.join("\n") + (entries.length ? "\n" : "") + "};\n";
// Idempotent write so the wrangler-dev watcher doesn't loop on its own output.
const prev = existsSync(outFile) ? readFileSync(outFile, "utf8") : null;
if (prev === next) {
  console.log(`gen-assets: ${entries.length} asset(s) unchanged`);
} else {
  writeFileSync(outFile, next);
  console.log(`gen-assets: wrote ${entries.length} asset(s) → src/assets.generated.ts`);
}
