// Auto-generated by scripts/copy-messages.js — do not edit manually
import csMessages from "./cs.json";
import daMessages from "./da.json";
import enMessages from "./en.json";
import fiMessages from "./fi.json";
import itMessages from "./it.json";
import nbMessages from "./nb.json";
import plMessages from "./pl.json";
import svMessages from "./sv.json";

export const messages: Record<string, Record<string, string>> = {
  cs: csMessages,
  da: daMessages,
  en: enMessages,
  fi: fiMessages,
  it: itMessages,
  nb: nbMessages,
  pl: plMessages,
  sv: svMessages,
};
