const fs = require("fs");
const path = require("path");

/**
 * Build script to convert the bundled client.js into a TypeScript module
 * This allows us to serve it inline, similar to how we handle CSS
 */

// Source file - built client bundle
const inputFile = path.resolve(__dirname, "dist/client.js");

// Destination file - TypeScript module
const outputFile = path.resolve(__dirname, "src/client/client-bundle.ts");

// Check if the input file exists
if (!fs.existsSync(inputFile)) {
  console.error(`Error: Client bundle not found at ${inputFile}`);
  console.error("Make sure to run 'vite build --mode client' first");
  process.exit(1);
}

// Read the bundled client.js
const clientJs = fs.readFileSync(inputFile, "utf8");

// Create the TypeScript module content
const moduleContent = `// This file is auto-generated by build-client.js
// Do not edit manually - it will be overwritten on build

export const clientJs = ${JSON.stringify(clientJs)};
`;

// Write the TypeScript module
fs.writeFileSync(outputFile, moduleContent, "utf8");

console.log(`Client bundle converted successfully: ${outputFile}`);
console.log(`Bundle size: ${(clientJs.length / 1024).toFixed(2)} KB`);
