import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core";

export const logs = sqliteTable("logs", {
  log_id: text("log_id", { length: 21 }).primaryKey(),
  category: text("category", { length: 255 }),
  tenant_id: text("tenant_id", { length: 64 }),
  user_id: text("user_id", { length: 64 }),
  ip: text("ip", { length: 255 }),
  type: text("type", { length: 8 }).notNull(),
  date: text("date", { length: 25 }).notNull(),
  client_id: text("client_id", { length: 255 }),
  client_name: text("client_name", { length: 255 }),
  user_agent: text("user_agent", { length: 255 }),
  description: text("description", { length: 255 }),
  details: text("details", { length: 2048 }),
  isMobile: integer("isMobile"),
  user_name: text("user_name", { length: 255 }),
  connection: text("connection", { length: 255 }),
  connection_id: text("connection_id", { length: 255 }),
  audience: text("audience", { length: 255 }),
  scope: text("scope", { length: 255 }),
  strategy: text("strategy", { length: 255 }),
  strategy_type: text("strategy_type", { length: 255 }),
  hostname: text("hostname", { length: 255 }),
  auth0_client: text("auth0_client", { length: 8192 }),
  session_connection: text("session_connection", { length: 255 }),
  country_code: text("country_code", { length: 2 }),
  city_name: text("city_name", { length: 255 }),
  latitude: text("latitude", { length: 255 }),
  longitude: text("longitude", { length: 255 }),
  time_zone: text("time_zone", { length: 255 }),
  continent_code: text("continent_code", { length: 2 }),
}, (table) => [
  index("logs_user_id").on(table.user_id),
  index("logs_tenant_id").on(table.tenant_id),
  index("logs_date").on(table.date),
  index("IDX_logs_tenant_date_type_user").on(table.tenant_id, table.date, table.type, table.user_id),
]);
