import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";

export const tenants = sqliteTable("tenants", {
  id: text("id", { length: 255 }).primaryKey(),
  name: text("name", { length: 255 }),
  audience: text("audience", { length: 255 }),
  sender_email: text("sender_email", { length: 255 }),
  sender_name: text("sender_name", { length: 255 }),
  language: text("language", { length: 255 }),
  logo: text("logo", { length: 255 }),
  primary_color: text("primary_color", { length: 255 }),
  secondary_color: text("secondary_color", { length: 255 }),
  created_at: text("created_at", { length: 255 }).notNull(),
  updated_at: text("updated_at", { length: 255 }).notNull(),
  support_url: text("support_url", { length: 255 }),
  idle_session_lifetime: integer("idle_session_lifetime"),
  session_lifetime: integer("session_lifetime"),
  session_cookie: text("session_cookie"),
  allowed_logout_urls: text("allowed_logout_urls"),
  ephemeral_session_lifetime: integer("ephemeral_session_lifetime"),
  idle_ephemeral_session_lifetime: integer("idle_ephemeral_session_lifetime"),
  default_redirection_uri: text("default_redirection_uri"),
  enabled_locales: text("enabled_locales"),
  default_directory: text("default_directory", { length: 255 }),
  error_page: text("error_page"),
  flags: text("flags"),
  friendly_name: text("friendly_name", { length: 255 }),
  picture_url: text("picture_url"),
  support_email: text("support_email", { length: 255 }),
  sandbox_version: text("sandbox_version", { length: 50 }),
  sandbox_versions_available: text("sandbox_versions_available"),
  legacy_sandbox_version: text("legacy_sandbox_version", { length: 50 }),
  change_password: text("change_password"),
  guardian_mfa_page: text("guardian_mfa_page"),
  device_flow: text("device_flow"),
  default_token_quota: text("default_token_quota"),
  default_audience: text("default_audience", { length: 255 }),
  default_organization: text("default_organization", { length: 255 }),
  sessions: text("sessions"),
  oidc_logout: text("oidc_logout"),
  allow_organization_name_in_authentication_api: integer("allow_organization_name_in_authentication_api"),
  customize_mfa_in_postlogin_action: integer("customize_mfa_in_postlogin_action"),
  acr_values_supported: text("acr_values_supported"),
  mtls: text("mtls"),
  pushed_authorization_requests_supported: integer("pushed_authorization_requests_supported"),
  authorization_response_iss_parameter_supported: integer("authorization_response_iss_parameter_supported"),
});

export const tenantSettings = sqliteTable("tenant_settings", {
  tenant_id: text("tenant_id", { length: 191 }).primaryKey().references(() => tenants.id, { onDelete: "cascade" }),
  idle_session_lifetime: integer("idle_session_lifetime"),
  session_lifetime: integer("session_lifetime"),
  session_cookie: text("session_cookie"),
  enable_client_connections: integer("enable_client_connections"),
  default_redirection_uri: text("default_redirection_uri"),
  enabled_locales: text("enabled_locales"),
  default_directory: text("default_directory", { length: 255 }),
  error_page: text("error_page"),
  flags: text("flags"),
  friendly_name: text("friendly_name", { length: 255 }),
  picture_url: text("picture_url"),
  support_email: text("support_email", { length: 255 }),
  support_url: text("support_url"),
  sandbox_version: text("sandbox_version", { length: 50 }),
  sandbox_versions_available: text("sandbox_versions_available"),
  change_password: text("change_password"),
  guardian_mfa_page: text("guardian_mfa_page"),
  default_audience: text("default_audience", { length: 255 }),
  default_organization: text("default_organization", { length: 255 }),
  sessions: text("sessions"),
});
